/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Testimonial = {
  _type: 'testimonial'
  quote: string
  attribution?: string
}

export type TableOfContents = {
  _type: 'tableOfContents'
  title?: string
}

export type SimpleBlockContent = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    external?: boolean
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type ResourceList = {
  _type: 'resourceList'
  showTableOfContents?: boolean
}

export type PressMentionList = {
  _type: 'pressMentionList'
  limit?: number
}

export type PostList = {
  _type: 'postList'
  limit?: number
}

export type LogoRow = {
  _type: 'logoRow'
  logos?: Array<
    {
      _key: string
    } & ContentImage
  >
}

export type LeaseCalculator = {
  _type: 'leaseCalculator'
  heading?: string
  intro?: string
  fieldLabel?: string
  amendmentDate?: string
  effectiveOffsetDays?: number
  milestones?: Array<
    {
      _key: string
    } & LeaseMilestone
  >
}

export type FootnoteList = {
  _type: 'footnoteList'
  title?: string
  footnotes?: Array<
    {
      _key: string
    } & Footnote
  >
}

export type FaqList = {
  _type: 'faqList'
  title?: string
}

export type Embed = {
  _type: 'embed'
  url: string
  title?: string
  width?: 'prose' | 'wide'
}

export type DonateButton = {
  _type: 'donateButton'
  hostedButtonId: string
  imageSrc?: string
  imageAlt?: string
  imageTitle?: string
}

export type Divider = {
  _type: 'divider'
  label?: string
}

export type CallToAction = {
  _type: 'callToAction'
  title?: string
  action: CtaAction
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        external?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & ContentImage)
  | ({
      _key: string
    } & LogoRow)
  | ({
      _key: string
    } & CallToAction)
  | ({
      _key: string
    } & Testimonial)
  | ({
      _key: string
    } & Embed)
  | ({
      _key: string
    } & DonateButton)
  | ({
      _key: string
    } & LeaseCalculator)
  | ({
      _key: string
    } & TableOfContents)
  | ({
      _key: string
    } & AssociationList)
  | ({
      _key: string
    } & ResourceList)
  | ({
      _key: string
    } & PressMentionList)
  | ({
      _key: string
    } & PostList)
  | ({
      _key: string
    } & FaqList)
  | ({
      _key: string
    } & FootnoteList)
  | ({
      _key: string
    } & Divider)
>

export type AssociationList = {
  _type: 'associationList'
  status?: 'active' | 'inactive'
  layout?: 'detailed' | 'list'
}

export type SocialLink = {
  _type: 'socialLink'
  platform: 'instagram' | 'facebook' | 'email'
  href: string
  label?: string
}

export type NavLink = {
  _type: 'navLink'
  label: string
  href: string
  external?: boolean
}

export type NavGroup = {
  _type: 'navGroup'
  label: string
  href: string
  links?: Array<
    {
      _key: string
    } & NavLink
  >
}

export type NavColumn = {
  _type: 'navColumn'
  title: string
  links: Array<
    {
      _key: string
    } & NavLink
  >
}

export type LeaseMilestone = {
  _type: 'leaseMilestone'
  days: number
  text: string
}

export type Footnote = {
  _type: 'footnote'
  number: number
  body: SimpleBlockContent
}

export type CtaAction = {
  _type: 'ctaAction'
  label: string
  href: string
  variant?: 'primary' | 'secondary' | 'ghost'
  size?: 'default' | 'large' | 'small'
  external?: boolean
}

export type ContentImage = {
  _type: 'contentImage'
  asset?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
  }
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  caption?: string
  width?: number
  height?: number
  variant?: 'default' | 'framed'
}

export type CarouselSlide = {
  _type: 'carouselSlide'
  image?: ContentImage
  caption?: string
}

export type TenantAssociation = {
  _id: string
  _type: 'tenantAssociation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  contactName?: string
  contactEmail?: string
  status: 'active' | 'inactive'
  order?: number
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  tagline?: string
  email?: string
  emailDisplay?: string
  logo?: ContentImage
  socials?: Array<
    {
      _key: string
    } & SocialLink
  >
  primaryNav?: Array<
    {
      _key: string
    } & NavGroup
  >
  mobileNav?: Array<
    {
      _key: string
    } & NavGroup
  >
  footerColumns?: Array<
    {
      _key: string
    } & NavColumn
  >
  legalLinks?: Array<
    {
      _key: string
    } & NavLink
  >
}

export type Resource = {
  _id: string
  _type: 'resource'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  href: string
  description?: string
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'resourceCategory'
  }
  order?: number
}

export type ResourceCategory = {
  _id: string
  _type: 'resourceCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  order?: number
}

export type PressMention = {
  _id: string
  _type: 'pressMention'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  publication?: string
  author?: string
  date: string
  link: string
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  date: string
  template?: 'questionnaire'
  body?: BlockContent
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  subtitle?: string
  width?: 'narrow' | 'prose' | 'wide' | 'expanded'
  prose?: boolean
  body?: BlockContent
  seoDescription?: string
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroTitle: string
  heroSubtitle?: string
  heroActions?: Array<
    {
      _key: string
    } & CtaAction
  >
  aboutBody?: BlockContent
  carousel?: Array<
    {
      _key: string
    } & CarouselSlide
  >
  joinHeading?: string
  joinBody?: BlockContent
  joinFormUrl?: string
  joinFormTitle?: string
  joinFormLinkLabel?: string
}

export type FaqItem = {
  _id: string
  _type: 'faqItem'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question: string
  answer: BlockContent
  order?: number
}

export type Campaign = {
  _id: string
  _type: 'campaign'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  subtitle?: string
  updatedAt?: string
  lede?: SimpleBlockContent
  body?: BlockContent
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Testimonial
  | TableOfContents
  | SimpleBlockContent
  | ResourceList
  | PressMentionList
  | PostList
  | LogoRow
  | LeaseCalculator
  | FootnoteList
  | FaqList
  | Embed
  | DonateButton
  | Divider
  | CallToAction
  | BlockContent
  | AssociationList
  | SocialLink
  | NavLink
  | NavGroup
  | NavColumn
  | LeaseMilestone
  | Footnote
  | CtaAction
  | ContentImage
  | CarouselSlide
  | TenantAssociation
  | SiteSettings
  | Resource
  | ResourceCategory
  | PressMention
  | Post
  | Page
  | HomePage
  | FaqItem
  | Campaign
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/app/(site)/[...slug]/page.tsx
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0]{  title,  subtitle,  width,  prose,  body,  seoDescription,    "associations": select(count(body[_type == "associationList"]) > 0 =>    *[_type == "tenantAssociation"] | order(order asc) {      _id, name, contactName, contactEmail, status    }),  "resourceCategories": select(count(body[_type == "resourceList"]) > 0 =>    *[_type == "resourceCategory"] | order(order asc) {      _id,      title,      "slug": slug.current,      "resources": *[_type == "resource" && category._ref == ^._id] | order(order asc) {        _id, title, href, description      }    }),  "pressMentions": select(count(body[_type == "pressMentionList"]) > 0 =>    *[_type == "pressMention"] | order(date desc) {      _id, title, publication, author, date, link    }),  "posts": select(count(body[_type == "postList"]) > 0 =>    *[_type == "post"] | order(date desc) {      _id, title, "slug": slug.current, date    }),  "faqItems": select(count(body[_type == "faqList"]) > 0 =>    *[_type == "faqItem"] | order(order asc) {      _id, question, answer    })}
export type PageBySlugQueryResult = {
  title: string
  subtitle: string | null
  width: 'expanded' | 'narrow' | 'prose' | 'wide' | null
  prose: boolean | null
  body: BlockContent | null
  seoDescription: string | null
  associations: Array<{
    _id: string
    name: string
    contactName: string | null
    contactEmail: string | null
    status: 'active' | 'inactive'
  }>
  resourceCategories: Array<{
    _id: string
    title: string
    slug: string
    resources: Array<{
      _id: string
      title: string
      href: string
      description: string | null
    }>
  }>
  pressMentions: Array<{
    _id: string
    title: string
    publication: string | null
    author: string | null
    date: string
    link: string
  }>
  posts: Array<{
    _id: string
    title: string
    slug: string
    date: string
  }>
  faqItems: Array<{
    _id: string
    question: string
    answer: BlockContent
  }>
} | null
// Variable: pageSlugsQuery
// Query: *[_type == "page"].slug.current
export type PageSlugsQueryResult = Array<string>

// Source: ./src/app/(site)/blog/[slug]/page.tsx
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0]{  title,  date,  template,  body,    "associations": select(count(body[_type == "associationList"]) > 0 =>    *[_type == "tenantAssociation"] | order(order asc) {      _id, name, contactName, contactEmail, status    }),  "resourceCategories": select(count(body[_type == "resourceList"]) > 0 =>    *[_type == "resourceCategory"] | order(order asc) {      _id,      title,      "slug": slug.current,      "resources": *[_type == "resource" && category._ref == ^._id] | order(order asc) {        _id, title, href, description      }    }),  "pressMentions": select(count(body[_type == "pressMentionList"]) > 0 =>    *[_type == "pressMention"] | order(date desc) {      _id, title, publication, author, date, link    }),  "posts": select(count(body[_type == "postList"]) > 0 =>    *[_type == "post"] | order(date desc) {      _id, title, "slug": slug.current, date    }),  "faqItems": select(count(body[_type == "faqList"]) > 0 =>    *[_type == "faqItem"] | order(order asc) {      _id, question, answer    })}
export type PostBySlugQueryResult = {
  title: string
  date: string
  template: 'questionnaire' | null
  body: BlockContent | null
  associations: Array<{
    _id: string
    name: string
    contactName: string | null
    contactEmail: string | null
    status: 'active' | 'inactive'
  }>
  resourceCategories: Array<{
    _id: string
    title: string
    slug: string
    resources: Array<{
      _id: string
      title: string
      href: string
      description: string | null
    }>
  }>
  pressMentions: Array<{
    _id: string
    title: string
    publication: string | null
    author: string | null
    date: string
    link: string
  }>
  posts: Array<{
    _id: string
    title: string
    slug: string
    date: string
  }>
  faqItems: Array<{
    _id: string
    question: string
    answer: BlockContent
  }>
} | null
// Variable: postSlugsQuery
// Query: *[_type == "post"].slug.current
export type PostSlugsQueryResult = Array<string>

// Source: ./src/app/(site)/campaigns/[slug]/page.tsx
// Variable: campaignBySlugQuery
// Query: *[_type == "campaign" && slug.current == $slug][0]{  title,  subtitle,  updatedAt,  lede,  body,    "associations": select(count(body[_type == "associationList"]) > 0 =>    *[_type == "tenantAssociation"] | order(order asc) {      _id, name, contactName, contactEmail, status    }),  "resourceCategories": select(count(body[_type == "resourceList"]) > 0 =>    *[_type == "resourceCategory"] | order(order asc) {      _id,      title,      "slug": slug.current,      "resources": *[_type == "resource" && category._ref == ^._id] | order(order asc) {        _id, title, href, description      }    }),  "pressMentions": select(count(body[_type == "pressMentionList"]) > 0 =>    *[_type == "pressMention"] | order(date desc) {      _id, title, publication, author, date, link    }),  "posts": select(count(body[_type == "postList"]) > 0 =>    *[_type == "post"] | order(date desc) {      _id, title, "slug": slug.current, date    }),  "faqItems": select(count(body[_type == "faqList"]) > 0 =>    *[_type == "faqItem"] | order(order asc) {      _id, question, answer    })}
export type CampaignBySlugQueryResult = {
  title: string
  subtitle: string | null
  updatedAt: string | null
  lede: SimpleBlockContent | null
  body: BlockContent | null
  associations: Array<{
    _id: string
    name: string
    contactName: string | null
    contactEmail: string | null
    status: 'active' | 'inactive'
  }>
  resourceCategories: Array<{
    _id: string
    title: string
    slug: string
    resources: Array<{
      _id: string
      title: string
      href: string
      description: string | null
    }>
  }>
  pressMentions: Array<{
    _id: string
    title: string
    publication: string | null
    author: string | null
    date: string
    link: string
  }>
  posts: Array<{
    _id: string
    title: string
    slug: string
    date: string
  }>
  faqItems: Array<{
    _id: string
    question: string
    answer: BlockContent
  }>
} | null
// Variable: campaignSlugsQuery
// Query: *[_type == "campaign"].slug.current
export type CampaignSlugsQueryResult = Array<string>

// Source: ./src/app/(site)/layout.tsx
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{  title,  description,  tagline,  email,  emailDisplay,  logo,  socials,  primaryNav,  mobileNav,  footerColumns,  legalLinks}
export type SiteSettingsQueryResult = {
  title: string
  description: string | null
  tagline: string | null
  email: string | null
  emailDisplay: string | null
  logo: ContentImage | null
  socials: Array<
    {
      _key: string
    } & SocialLink
  > | null
  primaryNav: Array<
    {
      _key: string
    } & NavGroup
  > | null
  mobileNav: Array<
    {
      _key: string
    } & NavGroup
  > | null
  footerColumns: Array<
    {
      _key: string
    } & NavColumn
  > | null
  legalLinks: Array<
    {
      _key: string
    } & NavLink
  > | null
} | null

// Source: ./src/app/(site)/page.tsx
// Variable: homePageQuery
// Query: *[_type == "homePage" && _id == "homePage"][0]{  heroTitle,  heroSubtitle,  heroActions,  aboutBody,  carousel,  joinHeading,  joinBody,  joinFormUrl,  joinFormTitle,  joinFormLinkLabel}
export type HomePageQueryResult = {
  heroTitle: string
  heroSubtitle: string | null
  heroActions: Array<
    {
      _key: string
    } & CtaAction
  > | null
  aboutBody: BlockContent | null
  carousel: Array<
    {
      _key: string
    } & CarouselSlide
  > | null
  joinHeading: string | null
  joinBody: BlockContent | null
  joinFormUrl: string | null
  joinFormTitle: string | null
  joinFormLinkLabel: string | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "page" && slug.current == $slug][0]{\n  title,\n  subtitle,\n  width,\n  prose,\n  body,\n  seoDescription,\n  \n  "associations": select(count(body[_type == "associationList"]) > 0 =>\n    *[_type == "tenantAssociation"] | order(order asc) {\n      _id, name, contactName, contactEmail, status\n    }),\n  "resourceCategories": select(count(body[_type == "resourceList"]) > 0 =>\n    *[_type == "resourceCategory"] | order(order asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      "resources": *[_type == "resource" && category._ref == ^._id] | order(order asc) {\n        _id, title, href, description\n      }\n    }),\n  "pressMentions": select(count(body[_type == "pressMentionList"]) > 0 =>\n    *[_type == "pressMention"] | order(date desc) {\n      _id, title, publication, author, date, link\n    }),\n  "posts": select(count(body[_type == "postList"]) > 0 =>\n    *[_type == "post"] | order(date desc) {\n      _id, title, "slug": slug.current, date\n    }),\n  "faqItems": select(count(body[_type == "faqList"]) > 0 =>\n    *[_type == "faqItem"] | order(order asc) {\n      _id, question, answer\n    })\n}': PageBySlugQueryResult
    '*[_type == "page"].slug.current': PageSlugsQueryResult
    '*[_type == "post" && slug.current == $slug][0]{\n  title,\n  date,\n  template,\n  body,\n  \n  "associations": select(count(body[_type == "associationList"]) > 0 =>\n    *[_type == "tenantAssociation"] | order(order asc) {\n      _id, name, contactName, contactEmail, status\n    }),\n  "resourceCategories": select(count(body[_type == "resourceList"]) > 0 =>\n    *[_type == "resourceCategory"] | order(order asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      "resources": *[_type == "resource" && category._ref == ^._id] | order(order asc) {\n        _id, title, href, description\n      }\n    }),\n  "pressMentions": select(count(body[_type == "pressMentionList"]) > 0 =>\n    *[_type == "pressMention"] | order(date desc) {\n      _id, title, publication, author, date, link\n    }),\n  "posts": select(count(body[_type == "postList"]) > 0 =>\n    *[_type == "post"] | order(date desc) {\n      _id, title, "slug": slug.current, date\n    }),\n  "faqItems": select(count(body[_type == "faqList"]) > 0 =>\n    *[_type == "faqItem"] | order(order asc) {\n      _id, question, answer\n    })\n}': PostBySlugQueryResult
    '*[_type == "post"].slug.current': PostSlugsQueryResult
    '*[_type == "campaign" && slug.current == $slug][0]{\n  title,\n  subtitle,\n  updatedAt,\n  lede,\n  body,\n  \n  "associations": select(count(body[_type == "associationList"]) > 0 =>\n    *[_type == "tenantAssociation"] | order(order asc) {\n      _id, name, contactName, contactEmail, status\n    }),\n  "resourceCategories": select(count(body[_type == "resourceList"]) > 0 =>\n    *[_type == "resourceCategory"] | order(order asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      "resources": *[_type == "resource" && category._ref == ^._id] | order(order asc) {\n        _id, title, href, description\n      }\n    }),\n  "pressMentions": select(count(body[_type == "pressMentionList"]) > 0 =>\n    *[_type == "pressMention"] | order(date desc) {\n      _id, title, publication, author, date, link\n    }),\n  "posts": select(count(body[_type == "postList"]) > 0 =>\n    *[_type == "post"] | order(date desc) {\n      _id, title, "slug": slug.current, date\n    }),\n  "faqItems": select(count(body[_type == "faqList"]) > 0 =>\n    *[_type == "faqItem"] | order(order asc) {\n      _id, question, answer\n    })\n}': CampaignBySlugQueryResult
    '*[_type == "campaign"].slug.current': CampaignSlugsQueryResult
    '*[_type == "siteSettings" && _id == "siteSettings"][0]{\n  title,\n  description,\n  tagline,\n  email,\n  emailDisplay,\n  logo,\n  socials,\n  primaryNav,\n  mobileNav,\n  footerColumns,\n  legalLinks\n}': SiteSettingsQueryResult
    '*[_type == "homePage" && _id == "homePage"][0]{\n  heroTitle,\n  heroSubtitle,\n  heroActions,\n  aboutBody,\n  carousel,\n  joinHeading,\n  joinBody,\n  joinFormUrl,\n  joinFormTitle,\n  joinFormLinkLabel\n}': HomePageQueryResult
  }
}
